name: Execute git pull on remote ssh server(production server)

on: []
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Execute ssh command
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: "cd ${{ secrets.PATH }} && git pull"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 2222
